### ISSUE TITLE
Clarity on the baseline procedure

### ISSUE THREAD

**Issue by ekernf01** [const-ae/linear_perturbation_prediction-Paper#1]
Hi Dr. Ahlmann-Eltze,

I had trouble matching the code to the text, and I just have a simple question about that. I'm not sure if this is the right forum to ask -- please feel free to redirect. 

The paper says the linear baseline learns a K by K matrix W (eqn 1) using a procedure that involves only PCA and replacement of some PCA outputs by other PCA outputs -- no ridge regression or gradient descent. 
 
![image](https://github.com/user-attachments/assets/fa8af8f1-1263-42f1-b3ee-58335ba2f938)

The code in [run_linear_perturbation_prediction.R](https://github.com/const-ae/linear_perturbation_prediction-Paper/blob/fb56868e5149f849c74c9fe56c61f0770e0356ed/benchmark/src/run_linear_perturbation_prediction.R#L72) uses ridge regression in addition to PCA, and it learns a matrix of size K by the number of genes, not K by K.

The code itself makes a lot of sense but there seems to be a last step not described in the paper -- discard G and W and learn a replacement via ridge regression. Could you clarify?

Thanks very much, and congratulations on an important study that is garnering a lot of well-deserved attention. 

Eric Kernfeld

**Comment by const-ae** [comment]
Hi Eric,

> I had trouble matching the code to the text, and I just have a simple question about that. I'm not sure if this is the right forum to ask -- please feel free to redirect.

No, this is great. Thank you for reaching out.


First, the `run_linear_perturbation_prediction.R` is an outdated script. I included it in the repo by mistake and it isn't actually used anywhere. The linear model that is described in the paper is implemented in [run_linear_pretrained_model.R](https://github.com/const-ae/linear_perturbation_prediction-Paper/blob/main/benchmark/src/run_linear_pretrained_model.R). I am sorry for the confusion.

> The paper says the linear baseline learns a K by K matrix W (eqn 1) using a procedure that involves only PCA and replacement of some PCA outputs by other PCA outputs -- no ridge regression or gradient descent.

That is not quite accurate. The G and P (which in my code, I call `gene_emb` and `pert_emb`) are found with PCA. Then, I fit W using ridge regression (see eq. (3) and code [line 150](https://github.com/const-ae/linear_perturbation_prediction-Paper/blob/main/benchmark/src/run_linear_pretrained_model.R#L150)), which I solve with the [normal equations](https://stats.stackexchange.com/questions/69205/how-to-derive-the-ridge-regression-solution).

> The code in [run_linear_perturbation_prediction.R](https://github.com/const-ae/linear_perturbation_prediction-Paper/blob/fb56868e5149f849c74c9fe56c61f0770e0356ed/benchmark/src/run_linear_perturbation_prediction.R#L72) uses ridge regression in addition to PCA, and it learns a matrix of size K by the number of genes, not K by K.

Your description is correct for the `run_linear_perturbation_prediction.R`, but what I used is `run_linear_pretrained_model`. Again sorry about that.

I hope this clarifies things. Let me know if you have any other questions :)

Best,
Constantin

**Comment by ekernf01** [comment]
This is very helpful! I will take a look at the details and follow up if needed. Thank you.
